from app.api.schemas.schemas import TopicTypes


topic_type_dict = {
    "Binary Tree": TopicTypes.DATA_STRUCTURES,
    "Matrix": TopicTypes.DATA_STRUCTURES,
    "Array": TopicTypes.DATA_STRUCTURES,
    "Linked List": TopicTypes.DATA_STRUCTURES,
    "Monotonic Queue": TopicTypes.DATA_STRUCTURES,
    "String": TopicTypes.DATA_STRUCTURES,
    "Union Find": TopicTypes.DATA_STRUCTURES,
    "Binary Search Tree": TopicTypes.DATA_STRUCTURES,
    "Segment Tree": TopicTypes.DATA_STRUCTURES,
    "Hash Table": TopicTypes.DATA_STRUCTURES,
    "Binary Indexed Tree": TopicTypes.DATA_STRUCTURES,
    "Heap (Priority Queue)": TopicTypes.DATA_STRUCTURES,
    "Monotonic Stack": TopicTypes.DATA_STRUCTURES,
    "Graph": TopicTypes.DATA_STRUCTURES,
    "Tree": TopicTypes.DATA_STRUCTURES,
    "Trie": TopicTypes.DATA_STRUCTURES,
    "Ordered Set": TopicTypes.DATA_STRUCTURES,
    "Doubly-Linked List": TopicTypes.DATA_STRUCTURES,
    "Stack": TopicTypes.DATA_STRUCTURES,
    "Queue": TopicTypes.DATA_STRUCTURES,
    "Suffix Array": TopicTypes.DATA_STRUCTURES,
    "Sliding Window": TopicTypes.ALGORITHMS,
    "Two Pointers": TopicTypes.ALGORITHMS,
    "Divide and Conquer": TopicTypes.ALGORITHMS,
    "Radix Sort": TopicTypes.ALGORITHMS,
    "Topological Sort": TopicTypes.ALGORITHMS,
    "Minimum Spanning Tree": TopicTypes.ALGORITHMS,
    "Bucket Sort": TopicTypes.ALGORITHMS,
    "Line Sweep": TopicTypes.ALGORITHMS,
    "Breadth-First Search": TopicTypes.ALGORITHMS,
    "Counting Sort": TopicTypes.ALGORITHMS,
    "Quickselect": TopicTypes.ALGORITHMS,
    "Binary Search": TopicTypes.ALGORITHMS,
    "Sorting": TopicTypes.ALGORITHMS,
    "Depth-First Search": TopicTypes.ALGORITHMS,
    "Merge Sort": TopicTypes.ALGORITHMS,
    "String Matching": TopicTypes.CONCEPTS,
    "Reservoir Sampling": TopicTypes.CONCEPTS,
    "Bit Manipulation": TopicTypes.CONCEPTS,
    "Data Stream": TopicTypes.CONCEPTS,
    "Randomized": TopicTypes.CONCEPTS,
    "Database": TopicTypes.CONCEPTS,
    "Number Theory": TopicTypes.CONCEPTS,
    "Bitmask": TopicTypes.CONCEPTS,
    "Math": TopicTypes.CONCEPTS,
    "Rejection Sampling": TopicTypes.CONCEPTS,
    "Iterator": TopicTypes.CONCEPTS,
    "Eulerian Circuit": TopicTypes.CONCEPTS,
    "Enumeration": TopicTypes.CONCEPTS,
    "Biconnected Component": TopicTypes.CONCEPTS,
    "Greedy": TopicTypes.CONCEPTS,
    "Combinatorics": TopicTypes.CONCEPTS,
    "Probability and Statistics": TopicTypes.CONCEPTS,
    "Shortest Path": TopicTypes.CONCEPTS,
    "Hash Function": TopicTypes.CONCEPTS,
    "Geometry": TopicTypes.CONCEPTS,
    "Dynamic Programming": TopicTypes.CONCEPTS,
    "Counting": TopicTypes.CONCEPTS,
    "Prefix Sum": TopicTypes.CONCEPTS,
    "Strongly Connected Component": TopicTypes.CONCEPTS,
    "Rolling Hash": TopicTypes.CONCEPTS,
    "Recursion": TopicTypes.CONCEPTS,
    "Memoization": TopicTypes.CONCEPTS,
    "Backtracking": TopicTypes.CONCEPTS,
    "Design": TopicTypes.MISCELLANEOUS,
    "Brainteaser": TopicTypes.MISCELLANEOUS,
    "Simulation": TopicTypes.MISCELLANEOUS,
    "Concurrency": TopicTypes.MISCELLANEOUS,
    "Game Theory": TopicTypes.MISCELLANEOUS,
    "Shell": TopicTypes.MISCELLANEOUS,
    "Interactive": TopicTypes.MISCELLANEOUS
}
